### ISSUE TITLE
Minipass Write?

### ISSUE THREAD

**Issue by smurrayatwork** [npm/fs-minipass#4]
Hello!

I'm a little new to node server side code, so forgive me if this is a silly question but: how does WriteStream or WriteStreamSync use Minipass? I know the read streams extend from Minipass, and there's some bindings going on with fs, but I'm not seeing how the write classes use the minipass library at all. It seems like they're just using native functionality.

**Comment by isaacs** [comment]
That is correct, the write stream classes are not using Minipass, they're just EventEmitters.  There isn't much value to implementing the write streams as passthrough streams, because they don't need all the functionality around managing the data output.  They do implement the same API and semantics as Minipass streams, just without the readable parts.
